# Generated by Django 2.2.28 on 2025-02-08 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20250207_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='view',
            new_name='views',
        ),
    ]
